version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - DEBUG=true
      - API_HOST=0.0.0.0
      - API_PORT=8000
      - CORS_ORIGINS=http://localhost:3000,http://localhost:8000
      - AUDIO_CACHE_DIR=/app/audio_cache
      - LOG_LEVEL=INFO
      - LOG_FILE=/app/logs/docc.log
      - ELEVENLABS_API_KEY=${ELEVENLABS_API_KEY}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY}
      - GOOGLE_GENERATIVE_AI_API_KEY=${GOOGLE_GENERATIVE_AI_API_KEY}
      - XAI_API_KEY=${XAI_API_KEY}
      - AI_GATEWAY_API_KEY=${AI_GATEWAY_API_KEY}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
    env_file:
      - .env
    volumes:
      - ./backend:/app/backend
      - ./shared:/app/shared
      - audio_cache:/app/audio_cache
      - logs:/app/logs
      # Mount user's home directory to access repositories
      # Users can access repos via /host/home/[username]/path/to/repo
      - ${HOME}:/host/home:ro
      # Alternative: mount specific repositories directory
      # - ~/repositories:/repositories:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - docc-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
      - WATCHPACK_POLLING=true
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/public:/app/public
      - /app/node_modules
    depends_on:
      - backend
    stdin_open: true
    tty: true
    restart: unless-stopped
    networks:
      - docc-network

volumes:
  audio_cache:
    driver: local
  logs:
    driver: local

networks:
  docc-network:
    driver: bridge
